framework:
  kernel:
    container: Os\Framework\DependencyInjection\Container
    environment: %APP_ENV%
  http:
    paths:
      controller: ['test/Controller', 'Test\Controller']
  dal:
    driver: Os\Framework\DataAbstractionLayer\Driver\PdoDriver
    access:
      type: %DATABASE_TYPE%
      host: %DATABASE_HOST%
      database: %DATABASE_DB%
      username: %DATABASE_USER%
      password: %DATABASE_PASS%
    paths:
      migration: ['test/Migration', 'Test\Migration']
      entity: ['test/Entity', 'Test\Entity']
      repository: ['test/Repository', 'Test\Repository']
  logger:
    directory: 'var/log'
    filenames:
      DEV:
        filename: 'dev'
        add_date: false
      PROD:
        filename: 'prod'
        add_date: true
  di:
    autoload: ['test']
    services:
      Os\Framework\DataAbstractionLayer\Driver\DriverInterface:
        class: Os\Framework\DataAbstractionLayer\Driver\PdoDriver