framework:
  kernel:
    container: Os\Framework\DependencyInjection\Container
    environment: %APP_ENV%
  http:
    paths:
      controller: ['src/Controller', 'App\Controller']
  dal:
    driver: Os\Framework\DataAbstractionLayer\Driver\PdoDriver
    access:
      type: %DATABASE_TYPE%
      host: %DATABASE_HOST%
      database: %DATABASE_DB%
      username: %DATABASE_USER%
      password: %DATABASE_PASS%
    paths:
      migration: ['src/Migration', 'App\Migration']
      entity: ['src/Entity', 'App\Entity']
      repository: ['src/Repository', 'App\Repository']
  logger:
    directory: 'var/log'
    filenames:
      DEV:
        filename: 'dev'
        add_date: false
      PROD:
        filename: 'prod'
        add_date: true
  di:
    autoload: ['src']
    services:
      Os\Framework\DataAbstractionLayer\Driver\DriverInterface:
        class: Os\Framework\DataAbstractionLayer\Driver\PdoDriver